In [1]:
import numpy as np

In [5]:
myarr= np.array([2,3,4,5], np.int8)

In [6]:
myarr

array([2, 3, 4, 5], dtype=int8)

In [7]:
myarr.dtype

dtype('int8')

In [8]:
myarr[2]

4

In [9]:
myarr2=np.array([[2,3,4,5]])# 2d array

In [10]:
myarr2[0,1]

3

In [11]:
myarr2.shape

(1, 4)

In [12]:
myarr2.dtype

dtype('int32')

In [13]:
myarr2[0,1]=67

In [14]:
myarr2

array([[ 2, 67,  4,  5]])

#### Array Creation 

In [15]:
list_arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
list_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
list_arr.dtype

dtype('int32')

In [17]:
list_arr.shape

(3, 3)

In [18]:
list_arr.size

9

In [19]:
list_arr[2,1]=10
list_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 10,  9]])

In [21]:
np.array({23,4,5,6})

array({4, 5, 6, 23}, dtype=object)

## 2

In [23]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
zeros = np.zeros((2,3), dtype='int32')
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
zeros.dtype

dtype('int32')

In [26]:
zeros.shape

(2, 3)

In [28]:
arng = np.arange(15)

In [29]:
arng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
lspace = np.linspace(1,50,10) 
# will provide 10 equi spaced elements from 1 to 50 

In [33]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [41]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [45]:
emp = np.empty((4,6))
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [46]:
emp_like= np.empty_like(lspace)
# creates empty array of the size of previous aray

In [47]:
emp_like

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
emp_like.shape

(10,)

In [49]:
ide = np.identity(3) # identity matrix

In [50]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
ide.shape

(3, 3)

In [52]:
arr = np.arange(99)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [55]:
arr= arr.reshape(3,33)

In [56]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [57]:
arr.shape

(3, 33)

In [58]:
arr =  arr.ravel() # to create 1d array

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [60]:
arr.shape

(99,)

####  Axis

In [64]:
x= [[1,2,3],[4,5,6],[7,1,0]]

In [65]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
ar.sum(axis=0) # row

array([12,  8,  9])

In [67]:
ar.sum(axis=1) #col

array([ 6, 15,  8])

In [68]:
ar.T #transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [69]:
ar.flat

In [70]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [71]:
ar.ndim

2

In [72]:
ar.size

9

In [75]:
ar.itemsize

4

In [73]:
ar.nbytes # total storage

36

In [74]:
ar.size*ar.itemsize

36

In [76]:
one= np.array([3,4,5,67,9])

In [77]:
one.argmax() #location

3

In [78]:
one.argmin()

0

In [79]:
 one.argsort() # returns indices to sort array

array([0, 1, 2, 4, 3], dtype=int64)

In [80]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [81]:
ar.argsort() # index

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [82]:
ar.argmin() # index

8

In [83]:
ar.argmax()

6

In [84]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [85]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [86]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [87]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [88]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [89]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [90]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [91]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [92]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [97]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [93]:
ar2 = np.array([[3, 6, 1],[4, 0, 3],[2, 8,4]])

In [94]:
ar2

array([[3, 6, 1],
       [4, 0, 3],
       [2, 8, 4]])

In [95]:
ar+ar2

array([[4, 8, 4],
       [8, 5, 9],
       [9, 9, 4]])

In [96]:
ar*ar2 # element wise : ar[0][0*ar2[0][0]

array([[ 3, 12,  3],
       [16,  0, 18],
       [14,  8,  0]])

In [98]:
np.sqrt(ar2)

array([[1.73205081, 2.44948974, 1.        ],
       [2.        , 0.        , 1.73205081],
       [1.41421356, 2.82842712, 2.        ]])

In [99]:
ar.sum()

29

In [100]:
ar.max()

7

In [101]:
ar.min()

0

In [102]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [104]:
w = np.where(ar>5) #new

In [105]:
w # in which position value>5 ?

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [107]:
type(w)

tuple

In [108]:
np.count_nonzero(ar)

8

In [110]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [111]:
ar[1,2]=0

In [112]:
np.nonzero(ar) # tuple of indices

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [113]:
import sys

In [114]:
py_ar = [0,3,43,5]

In [115]:
np_ar =np.array(py_ar)

In [116]:
sys.getsizeof(1)*len(py_ar) # size of list array in bytes

112

In [117]:
np_ar.itemsize*np_ar.size # size of numpy array

16

In [118]:
np_ar.tolist() # makes python list from numpy array

[0, 3, 43, 5]