In [1]:
import numpy as np

In [3]:
a= np.array([2,3,4])
print(a)

[2 3 4]


In [6]:
b= np.array([[9.0,3.0,8.0],[4.0,6.5,3.1]])
print(b)

[[9.  3.  8. ]
 [4.  6.5 3.1]]


In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
b.shape

(2, 3)

In [10]:
a.shape

(3,)

In [11]:
# type
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('float64')

In [13]:
c=np.array([3,4,5], dtype='int8')

In [14]:
c.dtype

dtype('int8')

In [15]:
#size
a.itemsize

4

In [16]:
a.size

3

In [17]:
a.size*a.itemsize # total size

12

In [19]:
a.nbytes # total

12

In [20]:
b.nbytes

48

In [21]:
b.itemsize

8

### Changing elements

In [22]:
a= np.array([[1,2,3,45,6,7,3],[4,5,6,43,56,78,21]])
print(a)

[[ 1  2  3 45  6  7  3]
 [ 4  5  6 43 56 78 21]]


In [23]:
a.shape

(2, 7)

In [24]:
a[1,5]

78

In [25]:
a[1,-2]

78

In [26]:
a[0,:] # 0th row

array([ 1,  2,  3, 45,  6,  7,  3])

In [27]:
a[:,2] #2nd column

array([3, 6])

In [ ]:
#[start index: final index : step size]

In [28]:
a[0,1:6:2]

array([ 2, 45,  7])

In [29]:
a[0,1:-1:2]

array([ 2, 45,  7])

In [30]:
a[1,5]=20

In [31]:
print(a)

[[ 1  2  3 45  6  7  3]
 [ 4  5  6 43 56 20 21]]


In [32]:
a[:,2]=100
a

array([[  1,   2, 100,  45,   6,   7,   3],
       [  4,   5, 100,  43,  56,  20,  21]])

In [33]:
a[:,2]=[200,300]
a

array([[  1,   2, 200,  45,   6,   7,   3],
       [  4,   5, 300,  43,  56,  20,  21]])

In [34]:
# 3d
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
# to get specific element work on outside in

b[0,1,1] # which one, which row, which col

4

In [36]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [37]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [38]:
b[1,1,0]

7

In [39]:
b[:,1,:]=[[10,20],[30,40]]

In [40]:
b

array([[[ 1,  2],
        [10, 20]],

       [[ 5,  6],
        [30, 40]]])

#### Initialize arrays

In [41]:
zeros= np.zeros(5)

In [42]:
zeros

array([0., 0., 0., 0., 0.])

In [43]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.zeros((2,3,3))  # 3d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [48]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [49]:
# initialize with any other number
np.full((2,2),99) # shape,value

array([[99, 99],
       [99, 99]])

In [52]:
a= np.array([[1,2,3,45,6,7,3],[4,5,6,43,56,78,21]])
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [53]:
np.full(a.shape,8)

array([[8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8]])

In [55]:
# random
np.random.rand(4,2)

array([[0.48126675, 0.06573603],
       [0.84550018, 0.82460501],
       [0.48287793, 0.97943379],
       [0.97124897, 0.25762146]])

In [56]:
np.random.randint(0,100,size=(2,3))

array([[57, 92, 99],
       [71, 35,  9]])

In [57]:
np.random.random_sample(a.shape)

array([[0.70655672, 0.45877141, 0.85063675, 0.01336494, 0.7393566 ,
        0.76709859, 0.7169322 ],
       [0.70863833, 0.64929771, 0.82142547, 0.22313161, 0.17012674,
        0.64190599, 0.95062375]])

In [58]:
np.random.randint(100,size=(2,3))

array([[50, 41, 91],
       [39, 95, 38]])

In [59]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
# repeat array
ar= np.array([[1,2,3]])
rep=np.repeat(ar,3)
rep

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [66]:
rep=np.repeat(ar,3,axis=0)
rep

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [67]:
rep=np.repeat(ar,3,axis=1)
rep

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [71]:
one= np.ones((5,5))
zero=np.zeros((3,3))
zero[1,1]=9
print(one)
print(zero)
one[1:4,1:4]=zero
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [72]:
# Copying

a= np.array([1,2,3])
b=a
b

array([1, 2, 3])

In [73]:
b[0]=23
b

array([23,  2,  3])

In [74]:
a # a changed

array([23,  2,  3])

In [75]:
c= a.copy()
c

array([23,  2,  3])

In [76]:
c[0]=40
c

array([40,  2,  3])

In [77]:
a # a not changed as we copied to c

array([23,  2,  3])

####  Math

In [78]:
a= np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [79]:
a*2

array([2, 4, 6, 8])

In [80]:
a+2

array([3, 4, 5, 6])

In [81]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [84]:
a+=3

In [85]:
a

array([6, 7, 8, 9])

In [86]:
a**2

array([36, 49, 64, 81], dtype=int32)

In [87]:
b= np.array([1,0,1,0])
a+b

array([7, 7, 9, 9])

In [88]:
np.sin(a)

array([-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [89]:
np.cos(a)

array([ 0.96017029,  0.75390225, -0.14550003, -0.91113026])

#### Algebra

In [90]:
a= np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [92]:
b=np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [94]:
c= np.matmul(a,b)
c

array([[6., 6.],
       [6., 6.]])

In [96]:
# determinant
d= np.identity(3)
np.linalg.det(d)

1.0

#### Statistics

In [97]:
s= np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
s.min()

1

In [100]:
np.min(s)

1

In [101]:
np.max(s)

6

In [102]:
s.max()

6

In [103]:
np.min(s, axis=1)

array([1, 4])

In [104]:
np.min(s, axis=0)

array([1, 2, 3])

In [105]:
np.sum(s)

21

In [106]:
s.sum()

21

In [107]:
np.sum(s,axis= 0)

array([5, 7, 9])

In [108]:
s.sum(axis=0)

array([5, 7, 9])

#### Reorganizing arrays

In [109]:
before= np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [111]:
after= before.reshape(8,1)
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [112]:
after= before.reshape(4,2)
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [113]:
after= before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [120]:
# vertically stacking
v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])
np.vstack((v1,v2)) # brackets 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [116]:
np.vstack((v1,v2,v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
# horizontal
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

###  Miscellaneous

##### Load data from file

In [121]:
d= np.genfromtxt('data.txt', delimiter=',')
d

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [122]:
d.astype('int32')

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [123]:
d

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [124]:
d= d.astype('int32')
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

#### Boolean masking and advanced indexing

In [125]:
d>15

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [126]:
d[d>15] # returns values for which condition is valid
# indexing

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [127]:
# indexing possible with a list in numpy

In [129]:
a= np.array([1,2,3,4,5,6,7,8,9])
a[[2,6,8]] # indexing using list

array([3, 7, 9])

In [130]:
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [131]:
np.any(d>15, axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [132]:
np.any(d>15, axis=1)

array([False,  True,  True])

In [133]:
np.all(d>15, axis=0)

array([False, False, False, False, False, False, False, False, False,
       False])

In [134]:
np.all(d>15, axis=1)

array([False, False,  True])

In [135]:
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [136]:
((d>12)&(d<22))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False]])

In [137]:
~((d>12)&(d<22))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [141]:
a= np.random.randint(30,size=(6,5))
a

array([[15, 13,  5, 20, 23],
       [28,  3, 14, 24,  0],
       [28,  6,  4,  6,  0],
       [10,  8, 13,  8, 23],
       [10, 25, 26,  7, 21],
       [ 7,  1, 15, 20, 18]])

In [142]:
a[2:4,0:2]

array([[28,  6],
       [10,  8]])

In [143]:
a[0:4,1:]

array([[13,  5, 20, 23],
       [ 3, 14, 24,  0],
       [ 6,  4,  6,  0],
       [ 8, 13,  8, 23]])

In [144]:
a[[0,1,2,3],[1,2,3,4]]

array([13, 14,  6, 23])

In [150]:
a[[0,4,5],3:]

array([[20, 23],
       [ 7, 21],
       [20, 18]])